### ISSUE TITLE
HOTFIX: Solucionado mala implementación de repositorio de control en Tests de User.

### ISSUE THREAD

**Issue by iangmenpor** [iangmenpor/Digital-Library#20]
## Descripción 🖊️
- Parece que ha habido una confusión en la implementación de los stubs. El stub debe simular el comportamiento de las clases reales que implementan las interfaces relevantes para tus pruebas unitarias.
-  Dado que se esta probando los casos de uso que interactúan con el UserDataRepository, sería más apropiado crear un stub para esta clase en lugar de para el DataSourceRepository. Este stub de UserDataRepository implementaría la interfaz UserRepository, que es la interfaz que realmente usan tus casos de uso para interactuar con los datos de usuario.

## Implementación ⚙️
- Crear clase Stub de UserDataRepository  (*Test/Data*).
- Implementar interfaz UserRepository para realizar llamadas a los métodos de los casos de uso. (*Test/Data*)
- Modificar todos los métodos test de las pruebas para que trabajar con repositorio de control de pruebas correcto. (*Test/Dominio*)
## Definición de Hecho (DoD) ✅
- [x] Se han modificado todos los métodos para que implementen Stub de UserDataRepository.
- [x] Se pase todas las pruebas.

**Comment by Irillium** [comment]
🤓☝
